---
abstract: 'various DOAP-related roles for Dist::Inkt'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Inkt-DOAP
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Dist::Inkt::DOAP:
    file: lib/Dist/Inkt/DOAP.pm
    version: 0.016
  Dist::Inkt::Role::DetermineRightsFromRdf:
    file: lib/Dist/Inkt/Role/DetermineRightsFromRdf.pm
    version: 0.016
  Dist::Inkt::Role::ProcessDOAP:
    file: lib/Dist/Inkt/Role/ProcessDOAP.pm
    version: 0.016
  Dist::Inkt::Role::ProcessDOAPDeps:
    file: lib/Dist/Inkt/Role/ProcessDOAPDeps.pm
    version: 0.016
  Dist::Inkt::Role::RDFModel:
    file: lib/Dist/Inkt/Role/RDFModel.pm
    version: 0.016
  Dist::Inkt::Role::ReadMetaDir:
    file: lib/Dist/Inkt/Role/ReadMetaDir.pm
    version: 0.016
  Dist::Inkt::Role::WriteCOPYRIGHT:
    file: lib/Dist/Inkt/Role/WriteCOPYRIGHT.pm
    version: 0.016
  Dist::Inkt::Role::WriteCREDITS:
    file: lib/Dist/Inkt/Role/WriteCREDITS.pm
    version: 0.016
  Dist::Inkt::Role::WriteChanges:
    file: lib/Dist/Inkt/Role/WriteChanges.pm
    version: 0.016
  Dist::Inkt::Role::WriteDOAP:
    file: lib/Dist/Inkt/Role/WriteDOAP.pm
    version: 0.016
requires:
  Dist::Inkt: 0.001
  MooX::Struct: 0
  Moose: 2.0800
  RDF::DOAP::Project: 0.007
  RDF::Trine: 1.000
  RDF::TrineX::Functions: 0
  RDF::TrineX::Parser::Pretdsl: 0.205
  RDF::TrineX::Serializer::MockTurtleSoup: 0
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Dist-Inkt-DOAP/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Dist-Inkt-DOAP
  homepage: https://metacpan.org/release/Dist-Inkt-DOAP
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-dist-inkt-doap.git
version: 0.016
